"""
config.py — Shared configuration (single source of truth for data/model shape).

Import what you need:

    from util.config import LOOKBACK_WEEKS, OUT_CHANNELS, BATCH_SIZE, LABEL

DEPLOYMENT NOTE (which of these matter at inference time)
---------------------------------------------------------
This file is copied verbatim from the research project, so it also carries
TRAINING-only knobs that the digital twin never uses. What the live/inference
path actually depends on:

  * IN_CHANNELS (40), OUT_CHANNELS (8)  — input/output tensor shape. MUST match
    the checkpoint (the notebooks read these from the checkpoint's own `config`
    and only fall back to these constants).
  * N_LAT (50), N_LON (360), N_NODES    — grid geometry (18,000 nodes, row-major).
  * LOOKBACK_WEEKS (4)                   — how many past weeks form one input window.
  * TIME_RESOLUTION ("weekly")           — daily .nc files are coarsened to weekly;
    MUST match the checkpoint's resolution or the model sees the wrong cadence.
  * LABEL / TASK ("sic")                 — the forecast target variable.

  IGNORED by the twin (training-only; kept so the copied model/data code imports
  cleanly): LEARNING_RATE, WEIGHT_DECAY, SCHEDULER, SCHED_*, WARMUP_EPOCHS,
  N_EPOCHS, PATIENCE, BATCH_SIZE (the inference batch size is set in the notebooks),
  SEED/set_seed, TRAIN_SPLIT/VAL_SPLIT (the deployed model's split is read from the
  checkpoint, not from here), GRID_CONNECTIVITY.

Change a value here ONLY if you are re-exporting artifacts to match a new model;
otherwise the checkpoint's stored config is authoritative.
"""

# ── Data ──────────────────────────────────────────────────────────────
N_INPUT_FEATURES = 10                                # input variables per node
LOOKBACK_WEEKS   = 4                                 # weeks of history as input
OUT_CHANNELS     = 8                                 # forecast horizon (weeks)
IN_CHANNELS      = N_INPUT_FEATURES * LOOKBACK_WEEKS # node feature dim: 40

# Grid dimensions (Antarctic 1° weekly). Used to build the grid-graph edge_index.
N_LAT = 50
N_LON = 360
N_NODES = N_LAT * N_LON

TRAIN_SPLIT      = 0.70
VAL_SPLIT        = 0.15

# Forecast target — one of {"sic", "sica"}.
#   "sic"  → label = "sea_ice_concentration", sigmoid output head,
#            climatology baseline = sic_climatology field
#   "sica" → label = "sic_anomaly",           linear output head,
#            climatology baseline = zeros (anomaly clim is 0 by definition)
TASK   = "sic"
_LABELS_BY_TASK = {
    "sic":  "sea_ice_concentration",
    "sica": "sic_anomaly",
}
LABEL = _LABELS_BY_TASK[TASK]

# Temporal resolution of the modelling task. The on-disk .nc files are DAILY
# (the authoritative, source-unchanged data); "weekly" derives weekly steps by
# a 7-day coarsen in load_nc_files. LOOKBACK_WEEKS / OUT_CHANNELS are counted in
# whichever unit this selects, so "weekly" => 4 weeks in, 8 weeks out.
TIME_RESOLUTION  = "weekly"                           # "weekly" or "daily"

# ── Graph construction ────────────────────────────────────────────────
# Selects which precomputed edge_index file `util.data_loader.build_edge_index`
# loads from disk. The files are generated by Code/super_pixel_edge_creator.ipynb
# and contain lattice edges + super-pixel hub edges baked together.
#   8  → loads edge_index_8conn.npy. Lattice = N/S/E/W + NE/NW/SE/SW diagonals.
#   4  → loads edge_index_4conn.npy. Lattice = N/S/E/W only.
# The multi-mesh models hold their own edges in multi_mesh_bundle.npz and
# ignore this lattice; it's kept for data-pipeline completeness.
GRID_CONNECTIVITY  = 8

# ── Training ──────────────────────────────────────────────────────────
BATCH_SIZE       = 2                                 # graphs per batch (GNNs are memory-heavy)
N_EPOCHS         = 300                               # with early stopping, so likely fewer

# Optimizer / LR schedule. Defaults are the multi_mesh Optuna HPO winner
# (30-trial search over lr / scheduler / weight_decay; see training_results/
# multi_mesh_hpo_best.json), so plain `python train.py --model X` reproduces it.
# train.py still exposes each as a CLI flag for overrides / new searches.
LEARNING_RATE    = 6.466422717414558e-4              # HPO winner (was 1e-4)
WEIGHT_DECAY     = 7.257005721594283e-4              # HPO winner AdamW weight decay (was 0.0)
SCHEDULER        = "plateau"                         # "plateau" (ReduceLROnPlateau) or "warmup_cosine"
SCHED_PATIENCE   = 7                                 # HPO winner plateau patience (was 3)
SCHED_FACTOR     = 0.5                               # ReduceLROnPlateau: LR multiplier on plateau
WARMUP_EPOCHS    = 5                                 # warmup_cosine: linear warmup length (epochs)
NUM_WORKERS      = 8                                 # DataLoader workers for parallel windowing
PATIENCE         = 30                                # early-stopping patience (epochs without val improvement)

# ── Reproducibility ───────────────────────────────────────────────────
SEED             = 42                                # default RNG seed (train.py/hpo.py --seed overrides)


def set_seed(seed: int = SEED):
    """Seed Python / NumPy / Torch (CPU+CUDA) and ask cuDNN to be deterministic, so
    weight init and data-shuffle order are reproducible. NOTE: PyG scatter / atomic
    CUDA ops have no deterministic kernels, so reruns are *near*-identical, not
    bit-exact — enough to remove the init/shuffle lottery, which is the point."""
    import os, random
    import numpy as np
    import torch
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    return seed
